service: aws-starter-go
frameworkVersion: '3'
useDotenv: true

# ============================
# Common
# ============================
provider:
  name: aws
  profile: ${self:service}-${opt:stage, 'dev'}  # AWS Profile Name(e.g.: aws-starter-go-dev)
  region: ap-northeast-1
  stage: "${opt:stage, 'dev'}"
  runtime: provided.al2
  iam:
    role:
      ${file(./serverless/iam/role.yml)}

plugins:
  - serverless-step-functions

package:
  individually: true
  patterns:
    - '!./**'
    - ./bin/**

# ============================
# Stage parameters
# ============================
params:
  dev:
    ${file(./serverless/param/dev.yml)}
  stg:
    ${file(./serverless/param/stg.yml)}
  prd:
    ${file(./serverless/param/prd.yml)}

# ============================
# Lambda
# ============================
functions:
  hello:
    ${file(./serverless/function/hello.yml)}
  hello2:
    ${file(./serverless/function/hello2.yml)}

resources:
  Resources:
    # ============================
    # DynamoDB
    # ============================
    waitlistTable:
      ${file(./serverless/dynamodb/waitlist.yml)}

    # ============================
    # LogGroup
    # ============================
    HelloWorldStateMachineLogGroup:  # NOTE: Specify the log group name for the state machine
      ${file(./serverless/loggroup/helloworldstatemachine.yml)}

    # ============================
    # VPC
    # ============================
    MyVPC:
      ${file(./serverless/vpc/vpc.yml)}
    MyInternetGateway:
      ${file(./serverless/vpc/internet_gateway.yml)}
    VPCGatewayAttachment:
      ${file(./serverless/vpc/vpc_gateway_attachment.yml)}
    MyElasticIp:
      ${file(./serverless/vpc/my_elastic_ip.yml)}
    MyNatGateway:
      ${file(./serverless/vpc/my_nat_gateway.yml)}
    # ============================
    # VPC(Private Subnet)
    # ============================
    PrivateSubnet:
      ${file(./serverless/vpc/private_subnet.yml)}
    PrivateRouteTable:
      ${file(./serverless/vpc/private_route_table.yml)}
    PrivateRoute:
      ${file(./serverless/vpc/private_route.yml)}
    SubnetRouteTableAssociationPrivateSubnet:
      ${file(./serverless/vpc/subnet_route_table_association_private.yml)}
    # ============================
    # VPC(Public Subnet)
    # ============================
    PublicSubnet:
      ${file(./serverless/vpc/public_subnet.yml)}
    PublicRouteTable:
      ${file(./serverless/vpc/public_route_table.yml)}
    PublicRoute:
      ${file(./serverless/vpc/public_route.yml)}
    SubnetRouteTableAssociationPublicSubnet:
      ${file(./serverless/vpc/subnet_route_table_association_public.yml)}

# ============================
# Step Functions
# ============================
stepFunctions:
  stateMachines:
    HelloWorldSateMachine:  # NOTE: Specify the state machine name
      ${file(./serverless/stepfunction/helloworld.yml)}
