service: aws-starter-go
frameworkVersion: '3'
useDotenv: true

# ============================
# Common
# ============================
provider:
  name: aws
  profile: ${self:service}-${opt:stage, 'dev'}  # AWSプロファイル名(例: aws-starter-go-dev)
  region: ap-northeast-1
  stage: "${opt:stage, 'dev'}"
  runtime: provided.al2
  iam:
    role:
      ${file(./serverless/iam/role.yml)}

plugins:
  - serverless-step-functions

package:
  individually: true
  patterns:
    - '!./**'
    - ./bin/**

# ============================
# Stage parameters
# ============================
params:
  dev:
    ${file(./serverless/param/dev.yml)}
  stg:
    ${file(./serverless/param/stg.yml)}
  prd:
    ${file(./serverless/param/prd.yml)}

# ============================
# Lambda
# ============================
functions:
  hello:
    ${file(./serverless/function/hello.yml)}
  hello2:
    ${file(./serverless/function/hello2.yml)}

resources:
  Resources:
    # ============================
    # DynamoDB
    # ============================
    waitlistTable:
      ${file(./serverless/dynamodb/waitlist.yml)}

    # ============================
    # LogGroup
    # ============================
    HelloWorldStateMachineLogGroup:  # NOTE: ステートマシンのロググループ名を指定する
      ${file(./serverless/loggroup/helloworldstatemachine.yml)}

# ============================
# Step Functions
# ============================
stepFunctions:
  stateMachines:
    HelloWorldSateMachine:  # NOTE: ステートマシン名を指定する
      ${file(./serverless/stepfunction/helloworld.yml)}
